export const homeObjOne ={
    id: "about",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium Bank',
    headline: "Unlimimited transactions",
    description: "Get acess to our exclusive service",
    buttonLabel: "GetStarted",
    imgStart: false,
    img: require('../../images/svg-1.svg'),
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
};